spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:./wizlineDB
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


author:
  mail: abrilrdev@gmail.com
  message: This API was realized by Oscar Abril. For contacting me abrilrdev@gmail.com